/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/otepadTheme.ts
 * Command: astryx theme build src/theme/otepadTheme.ts --out src/theme/otepad.css
 * Generated: 2026-10-07T12:35:15.052Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
