/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/otepadTheme.ts
 * Command: astryx theme build src/theme/otepadTheme.ts --out src/theme/otepad.css
 * Generated: 2026-07-29T00:42:12.833Z
 */

/// <reference path="./otepad.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const otepadTheme: DefinedTheme;
